### ISSUE TITLE
Autocomplete filling in $bucket_name for bucket name

### ISSUE THREAD

**Issue by russorat** [influxdata/vsflux#120]
I think it should fill in the "bucket_name" instead of the $bucket_name.

![Kapture 2020-03-02 at 13 10 41](https://user-images.githubusercontent.com/4805997/75718163-4ec38c00-5c87-11ea-956e-f9ef798b7c10.gif)

**Comment by jademcgough** [comment]
This was resolved by https://github.com/influxdata/flux-lsp/commit/311784ed3bea3fc8b0e2a163a05208a9439ec1c0
