### ISSUE TITLE
Should this plugin format flux code?

### ISSUE THREAD

**Issue by russorat** [influxdata/vsflux#123]
not sure if this should be here or in some prettify lib, but it would be really handy to auto format my flux script. connect https://github.com/influxdata/flux/issues/51

**Comment by kelwang** [comment]
yeah, let me rebase my old formatter branch, then we shall be ready to go

**Comment by jademcgough** [comment]
I'd like to have a discussion about where flux formatting should happen in the LSP stack.

@bthesorceror would it make more sense to support formatting in the language server, or should we keep that in the VSCode extension?

**Comment by jademcgough** [comment]
As of 3/9, this work is blocked by problems with comment formatting in the flux codebase.

**Comment by bthesorceror** [comment]
When we add the format messages for the LSP this should just work out of the box in VSCode

**Comment by jademcgough** [comment]
Closing this; the work will be done as part of https://github.com/influxdata/flux-lsp/issues/143
