### ISSUE TITLE
local wasm build launcher

### ISSUE THREAD

**Issue by kelwang** [influxdata/vsflux#125]
Make a custom debug launcher for local flux lsp wasm that copies the file from the other place

**Comment by bthesorceror** [comment]
when you are working with a local wasm build the wasm should be copied from `node_modules/@influxdata/flux-lsp-cli/node_modules/@influxdata/flux-lsp-node/flux-lsp-node_bg.wasm` but when running against a pinned npm version it should be `node_modules/@influxdata/flux-lsp-node/flux-lsp-node_bg`

**Comment by kelwang** [comment]
@bthesorceror , we no longer have flux-cli, we can just close it, right?
