### ISSUE TITLE
Database Connection: Cloud 2 URLs not appearing in dropdown

### ISSUE THREAD

**Issue by alsargent** [influxdata/vsflux#129]
Versions:
**Flux** 0.4.0
**VS Code** 
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

When I go to create a new database connection, the Cloud 2 URLs not appearing in dropdown

![image](https://user-images.githubusercontent.com/20701/76109591-969d2880-5f91-11ea-8c44-203a6ae09339.png)

**Comment by kelwang** [comment]
I researched this a little bit. What happens is html5 dataset will always filter the list.

There are 2 ways to fix this.
1. The easiest way, remove the default connection url for v2 connection. So it will always show the list if we try to add a new connection. But when editing an existing connection, you might still need to manually delete your input to see the entire list.

2. Write customized js & UI, to disable the filtering. jquery UI btw, has that option.

Any Suggestion, @russorat , @jademcgough , @bthesorceror ?

**Comment by kelwang** [comment]
after thought for a while, I decided to go with option one
