### ISSUE TITLE
Database Connection: error messages even though connection made

### ISSUE THREAD

**Issue by alsargent** [influxdata/vsflux#132]
**vs flux plugin**: 0.4.0
InfluxDB Cloud 2 AWS Oregon
**visual studio**
Version: 1.42.1
Commit: c47d83b293181d9be64f27ff093689e8e7aed054
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

When I open a Database Connection, in the output window I get a 400 error, even though the buckets are found.

![image](https://user-images.githubusercontent.com/20701/76110157-d6184480-5f92-11ea-964c-81ec6b996883.png)

**Comment by kelwang** [comment]
I can't reproduce this issue, but i will the fix the triple error message in this one

**Comment by jademcgough** [comment]
@alsargent If you still see this issue, can you reopen with steps to reproduce?
