### ISSUE TITLE
Database Connection: Show code in each cell in each dashboard

### ISSUE THREAD

**Issue by alsargent** [influxdata/vsflux#133]
A feature request: In the database pane, allow the user to see a list of all dashboards created, and for each dashboard, a list of all its cells. Then let the user click on a cell, and view/edit its flux code.

![image](https://user-images.githubusercontent.com/20701/76110457-6c4c6a80-5f93-11ea-9d20-8ea59e57afbf.png)

**Comment by kelwang** [comment]
great idea

**Comment by bthesorceror** [comment]
Given visualization is outside the scope of this plugin I think that editing cells would be an awkward experience and best done in the UI. Also this plugin is for both v1 and v2 and this would not be possible for v1.
