### ISSUE TITLE
Debug Non Tabular Data

### ISSUE THREAD

**Issue by rawkode** [influxdata/vsflux#158]
I'm currently working on some Flux functions for sending notifications to various third party services.

Doing this from VSCode with this plugin is fantastic, but it's very difficult to debug non tabular data.

I've been using `http.post` a fair bit to add these endpoints, and it's currently impossible to debug the response of this call; without having to drop to an HTTP client and sending the request manually.

It would be great if VSFlux could allow me to inspect / debug variables from the code editor, or even print them to the log output.

**Comment by bthesorceror** [comment]
My thought is that dumping this in the log would be a first start but that said I would like to get a settings page to turn this on and off. This way if you are not debugging a query you get a cleaner log experience.
