### ISSUE TITLE
Add Connect and Disconnect options in INFLUXDB menu

### ISSUE THREAD

**Issue by abalone23** [influxdata/vsflux#160]
I would like there to be an explicit `Connect` and `Disconnect` option when right clicking on an inflxudb connection:
<img width="412" alt="Screen Shot 2020-06-24 at 3 49 36 PM" src="https://user-images.githubusercontent.com/330044/85635327-770a3880-b632-11ea-82a8-d81ac6eafb99.png">

Currently there is just `Edit Connection` and `Remove Connection`

Workaround:
Double click on the connection name.

**Comment by bthesorceror** [comment]
This design follow patterns you see in other plugins, queries are send to which ever one show a blue influx logo. Also there is no idea of a persistent connection that you might see with something like Postgres or MySQL and rather it issues a http request to the query endpoint when a query is ran.
