### ISSUE TITLE
Flux queries no longer supported on V1 connections

### ISSUE THREAD

**Issue by jsmiller84** [influxdata/vsflux#162]
Up to vsflux version 0.5.2 I was able to connect to influxdb version 1.8 and use this plugin to run flux commands from a file. I am no longer able to do so and receive the following error.

Error: error parsing query: found FROM, expected SELECT, DELETE, SHOW, CREATE, DROP, EXPLAIN, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1

I tracked the code changes back to a request that was merged where V1 connections can no longer use the flux (/api/v2/query) endpoint, even though they are supported in Influxdb 1.7 and 1.8. 

If you have a V1 connection, you are now being limited to only the (/query) endpoint which only supports the basic influx query language.

**Comment by rbetts** [comment]
Related: https://github.com/influxdata/influxdb/issues/18947 ?

**Comment by rbetts** [comment]
@jsmiller84 Thanks for this report .. we can confirm and will get this resolved.

**Comment by bthesorceror** [comment]
this is fixed in the latest release (0.5.5)
