### ISSUE TITLE
Can't Edit or Remove connections

### ISSUE THREAD

**Issue by bland328** [influxdata/vsflux#171]
I'm using vsflux in VS Code 1.50.0 under macOS Catalina.

Add Connection worked fine to add two connections, but now I need to delete one of them, and find that both Edit Connection and Remove Connection result in errors like this one: 

`Command 'InfluxDB: Edit Connection' resulted in an error (Cannot read property 'edit' of undefined)`

I've un- and re-installed the plugin to no avail.

Can anyone give me a hint on where to look to manually delete one or both?

And is there additional information I might be able to collect to help figure out why Edit and Remove aren't working?

EDIT:
When I restart VS Code, I have to Add Connection again--so, it appears that either the connections I create are never actually saved (which could explain Edit and Remove not working), or at least that no default connection is remembered.

**Comment by nathanielc** [comment]
@bland328 Thanks for the report, we will take a look.

**Comment by scbrickley** [comment]
@bland328 We've got a PR up that should fix this issue: #181 

That will be included in the next release, which should come early next week.
