### ISSUE TITLE
Results tab does not visually partition tables

### ISSUE THREAD

**Issue by sanderson** [influxdata/vsflux#183]
When I run the following query:

```js
import "experimental/array"
import "experimental"

rows = [
  {_measurement: "test", _field: "foo", tag: "v1", _value: 1, _time: experimental.subDuration(d: 3m, from: now())},
  {_measurement: "test", _field: "foo", tag: "v1", _value: 2, _time: experimental.subDuration(d: 2m, from: now())},
  {_measurement: "test", _field: "foo", tag: "v2", _value: 3, _time: experimental.subDuration(d: 1m, from: now())},
  {_measurement: "test", _field: "foo", tag: "v2", _value: 4, _time: now()}
]

array.from(rows: rows)
  |> group(columns: ["tag"], mode: "by")
```

I get the following in my query output tab:

![image](https://user-images.githubusercontent.com/181484/99420288-49ac7880-28ba-11eb-92a1-3bf8c52921b4.png)

The results are accurate, but the structure of the table(s) do not accurately represent the structure of the results. This query returns a stream of tables containing two tables. To accurately represent the structure of the results, it should look like this:

![image](https://user-images.githubusercontent.com/181484/99420916-09012f00-28bb-11eb-9000-8e05bab948e3.png)

In the raw annotated CSV output, the `table` column identifies the table a row belongs to.

**Comment by rickspencer3** [comment]
Is this a duplicate or related to #227 ?
