### ISSUE TITLE
Option to disable SSL verification

### ISSUE THREAD

**Issue by Jujo100** [influxdata/vsflux#202]
There is no way to connect over HTTPS if the server certificate cannot be verified.

The influxdb-client-python package has a feature to disable SSL verification by passing 'verify_ssl=False' to the InfluxDBClient class. The same is also true when using the requests package.

When I try to connect to a server over HTTPS, VSCode shows the following error:
![image](https://user-images.githubusercontent.com/48825639/111604394-34464d00-87cd-11eb-9663-ac4c1cf8fd31.png)

I know this server is working OK since I have used influxdb-client-python with the same settings but with 'verify_ssl=False'

influxDB version: 2.0.4 (4e7a59b)
vsflux version: v0.5.17

Regards,
Justin.

**Comment by rockstar** [comment]
This can't be addressed until influxdata/influxdb-client-js#367 is fixed.

**Comment by sranka** [comment]
influxdata/influxdb-client-js#367 contains an example with a configuration option that skips TLS certificate verification, it works fine
