### ISSUE TITLE
trailing forward slash in Hostname and Port causes Failures

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/vsflux#225]
Steps:
 * Create a new connection, but keep the trailing "/", such as https://us-west-2-1.aws.cloud2.influxdata.com/
 * Click "Test"

Result: A message says that it failed to connect to the database
Expected: The database connection is successful

**Comment by scbrickley** [comment]
This was resolved in https://github.com/influxdata/vsflux/pull/229
