### ISSUE TITLE
Flux functions run in UI don't run in VS Code

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/vsflux#236]
The following function works in the UI but not in VS Code. No errors reported. 
```
import "experimental/usage"

usage.from(
    start: v.timeRangeStart,
    stop: v.timeRangeStop,
)
   |> filter(fn: (r) =>
      r._measurement == "http_request"
      and (r.endpoint == "/api/v2/write" or r.endpoint == "/write")
      and r._field == "req_bytes"
    )
```

**Comment by scbrickley** [comment]
On the latest release of the extension, running that query against my personal cloud account results in error output that reads:
```
[2021-07-12T15:30:28-04:00] - Error: error @4:12-4:13: undefined identifier v
```
The extension shows the error in the Flux output channel without me having to click anything or hit a keyboard shortcut.

When I change the `start` and `stop` parameters to valid timestamps or durations, the query works, and returns data if there is any.

Is there another query that reproduces this behavior, or are there details about your environment that might be relevant?

**Comment by Anaisdg** [comment]
Hello @scbrickley, 
It works, I think the conflict here was from learning that you can't query less than 1h of data with usage.from() if using the default raw=false. My mistake.
