### ISSUE TITLE
VSCode 1.57 breaks the plugin

### ISSUE THREAD

**Issue by nathanielc** [influxdata/vsflux#237]
We are getting reports that the newest version of VSCode (1.57.0) is breaking the Flux plugin. 

The solution should just be to change these two lines in to import ^1.57.0, and see what breaks and then fix it.

https://github.com/influxdata/vsflux/blob/81afd91ebf9764ecdd3a074c4f208dc48120e2f9/package.json#L26
https://github.com/influxdata/vsflux/blob/81afd91ebf9764ecdd3a074c4f208dc48120e2f9/package.json#L179

VSCode 1.57 release notes may have some helpful clues https://code.visualstudio.com/updates/v1_57

NOTE: We do not want to commit 1.57 as the minimum VSCode unless absolutely needed. Rather just change the version locally so we can test and fix the issues in backwards/forwards compatible way.

**Comment by scbrickley** [comment]
In addition to upgrading the dependencies, whoever picks this up will have to install the latest version of VS Code on their machines while they're debugging, and then downgrade back to an older version when they want to make sure they haven't broken anything.

To test your changes, open `vsflux` in VS Code, and run the extension in debugging mode by pressing `F5`.

**Comment by scbrickley** [comment]
Also, because the breaking changes seem to be related how VS Code renders our HTML, it might be helpful to know that our plugin uses [mustache.js](https://github.com/janl/mustache.js/) for some HTML templates.

**Comment by hoorayimhelping** [comment]
I'm not super familiar with the processes in this repo, but after looking into this, it seems like `1.57.0` is a breaking change for this plugin.

When using the latest version of VsCode,  `1.57.0`, plugin version `1.45.0` seems to throw errors after a while. When upgrading `@types/vscode` to `1.57.0`, it upgrades the engine to the same version and everything works. That build of the plugin doesn't seem to work on older versions of VSCode, it says version `1.57.0` is incompatible with this version.

I might have been doing the testing wrong though. I think I might need to meet with one of you guys over zoom to see what the process is.

**Comment by nathanielc** [comment]
@hoorayimhelping Thanks, sounds like we just need to update to 1.57.0. Thanks!
