### ISSUE TITLE
Intermittent 'Handler Already Set' error after running extension in debugging mode.

### ISSUE THREAD

**Issue by scbrickley** [influxdata/vsflux#250]
Since the 1.57 upgrade, the extension fails to load if I've recently run it in debugging mode.

When this occurs, no configs will be loaded in the explorer menu, and when I try to run one of the extension commands, I get this pop up:

![handler-err](https://user-images.githubusercontent.com/18431450/124157155-75a1f600-da66-11eb-8b7f-62ec824065e8.png)

I get something similar when, in the same session, I try to run the extension in debugging mode:

![handler-popup](https://user-images.githubusercontent.com/18431450/124157232-8a7e8980-da66-11eb-9784-b369442473f4.png)

Closing and restarting VS Code resolves the issue. If I run the extension in debugging mode again, close VS Code, and then start a new VS Code session, the bug returns.

**Comment by rockstar** [comment]
This appears to be microsoft/vscode#126339, which is fixed. We don't have a single instance of `setHandler` in our source at all, so is unlikely to be related to our plugin.
