### ISSUE TITLE
Reduce calls to the api

### ISSUE THREAD

**Issue by rockstar** [influxdata/vsflux#258]
The treeview on the left hand pane that shows the buckets will repeatedly call `getChildren` of the currently focused `INode` implementation. For instance, if you select a measurement, the keys that are associated with it are fetched once per second. Acknowledging that _maybe_ we want to update dynamically when keys change, even checking once per second is chatty. As I type this, VSCode is in the background making requests to the API every second.

Outstanding question: do we want dynamic update at all? Could we just cache and move on? If we want dynamic update, what is a better interval than once per second? Every 30 seconds? Every minute?

I will look into whether we can check if the VSCode window is active, so we can at least turn off updates when the browser window is minimized.

**Comment by barbaranelson** [comment]
For something like the list of buckets that won't change very frequently, I agree with reducing the frequency, maybe to at most once per minute.  Alternatively, you could just cache the list, and then if the user closes/reopens the drop down, re-fetch the bucket list.
