### ISSUE TITLE
Implement Debugger Extension for vsflux

### ISSUE THREAD

**Issue by rockstar** [influxdata/vsflux#293]
Currently, to run a flux script, there's a kinda hacky Ctrl+Shift+P->"InfluxDB: Run query" process to get a query to run. VSCode already provides a mechanism for running code, and that's the Run/Run & Debug flow (using F5 or however you'd like to run).

In order to support the native Run functionality, vsflux needs to implement a [Debugger extension](https://code.visualstudio.com/api/extension-guides/debugger-extension], and specifically implement a flux specific "Debug adapter" for flux.

This task is to produce a PR, but it's not entirely clear how direct that work is, so there is likely some exploratory work that will be included in this.

DOD:

  - Hit F5 to run Flux.

**Comment by alkuzad** [comment]
ctrl+alt+e runs flux query but you can change it to F5 easily in Keyboards Shorcuts configuration.

![obraz](https://user-images.githubusercontent.com/3463594/132809879-7af034f9-8921-4528-9f73-fde4a2b45f0a.png)
