### ISSUE TITLE
Include table name in output from yield and group records from the same table together

### ISSUE THREAD

**Issue by Anaisdg** [influxdata/vsflux#301]
The following Flux query:
```
common = from(bucket: "Air sensor sample dataset")
  |> range(start: 2021-08-19T19:23:37.000Z, stop: 2021-08-19T19:24:17.000Z)
  |> filter(fn: (r) => r["_measurement"] == "airSensors")
  |> filter(fn: (r) => r["_field"] == "co")
  |> filter(fn: (r) => r["sensor_id"] == "TLM0100" or r["sensor_id"] == "TLM0101")
  |> pivot(rowKey:["_time"], columnKey: ["sensor_id"], valueColumn: "_value") 
  |> yield(name: "common")

TLM0100 = common 
  |> aggregateWindow(every: 20s, fn: spread, column: "TLM0100")
  |> yield(name: "(max-min) of the sensor TLM0100")
  
TLM0101 = common 
  |> aggregateWindow(every: 1d, fn: spread, column: "TLM0101")
  |> yield(name: "(max-min) of the sensor TLM0101")
  ```
  Should yield three distinct outputs, identified by the name provided in the yield() function. 
Expectation:

<img width="1324" alt="Screen Shot 2021-09-15 at 3 42 29 PM" src="https://user-images.githubusercontent.com/30506042/133506549-f20d42ed-e53e-4ef3-af47-090ed1c0097e.png">

Instead the vs code extension produces the following output: 
<img width="966" alt="Screen Shot 2021-09-15 at 12 30 06 PM" src="https://user-images.githubusercontent.com/30506042/133506414-7393026d-dc37-40bf-85a5-04b3c311e022.png">
I can't easily tell which records which belong to which tables and what tables are which.

**Comment by rockstar** [comment]
This was fixed in the most recent release.
