### ISSUE TITLE
Add a Copy Script ID menu item

### ISSUE THREAD

**Issue by rickspencer3** [influxdata/vsflux#339]
When a user right-clicks on a bucket, a script, etc... vscode should present some information about the entity. For example, what is the id of the entity?

**Comment by onelson** [comment]
Planning to dig in on this tomorrow AM. Mostly I'll be using it as a vehicle to get more familiar with the vscode APIs and so on.

For the approach, an `About` action that presents the info in a panel or modal sounds like it could be a good first step. If the presentation/UX needs to change, at least we'd have the data handy to iterate with.

**Comment by onelson** [comment]
Reworking the scope a little bit after a discussion with @rickspencer3 and @rockstar.

I briefly looked at vscode's "show message" APIs but the modal we can present this way only accepts plain text (no nice formatting) and doesn't allow you to copy text. Part of the motivation for this feature was to be able to get the id of scripts so they could be invoked by other means, so it'd be annoying to be able to see the id and not copy it.

Adding a new virtual document, or webview to display the metadata for a resource could be an option, but it looks like there's some additional complexity in managing the lifetime of the panels in these cases. Not impossible but a little heavy.

We briefly discussed dumping the metadata out to the Output panel (essentially just logging it out). Seemed like this was a :-1: for UX.

Finally, it sounds like we settled on providing a _"copy script id"_ menu item for scripts (only scripts). This will push the id into the clipboard, and we can probably "toast" a quick message indicating this happened.
