### ISSUE TITLE
Saving a task should not close the task

### ISSUE THREAD

**Issue by abalone23** [influxdata/vsflux#343]
Using Flux extension v0.6.9
When I save a task it shows "Save and close". It shouldn't close the task when it's saved:
<img width="682" alt="Screen Shot 2021-11-12 at 1 50 03 PM" src="https://user-images.githubusercontent.com/330044/141538685-ce38138a-3a42-4018-8ad4-a13c102fb271.png">

**Comment by rockstar** [comment]
While I agree that the UX is not the best, and is a work-in-progress, the "save" of a task is putting something on a remote resource. The close is intended specifically to message that this isn't a trivial operation, and that you are essentially putting changes into production. Until we can figure out a better user experience, this is the best way to communicate that.
