### ISSUE TITLE
Connection fails us-east-1

### ISSUE THREAD

**Issue by daviddkkim** [influxdata/vsflux#345]
![Screen Shot 2021-11-15 at 4 24 39 PM](https://user-images.githubusercontent.com/12561526/141855845-8c0a62d5-15a0-4423-9e30-e1f103fb1815.png)

**Comment by Marwes** [comment]
Works fine when I test it so perhaps the certificate has been corrected now. Can you verify that it works now?

**Comment by Marwes** [comment]
Closing since it seems to be fixed, but feel free to re-open if it happens again!
