### ISSUE TITLE
Not possible to create New Connection when updated to Flux 0.6.12 or 0.6.13 extension

### ISSUE THREAD

**Issue by w4z** [influxdata/vsflux#375]
The INFLUXDB->(+) AddConnection from Explorer View does not work when a new connection is required.
The Wizard show 'Test' and 'Save' buttons as expected along the other fields, but when selecting Test or Save nothing happens.
After downgrading to Flex Extension 0.6.9 the wizard works correctly.

Visual Studio Code:
Version: 1.64.0
Commit: 5554b12acf27056905806867f251c859323ff7e9
Date: 2022-02-03T04:23:11.224Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.4.0-97-generic

**Comment by cailloumajor** [comment]
Same here with version 0.6.16
