### ISSUE TITLE
Research spike for launch.json support

### ISSUE THREAD

**Issue by rockstar** [influxdata/vsflux#387]
`launch.json` configuration and initial bootstrapping is detailed [in this document](https://code.visualstudio.com/docs/editor/debugging). However, we should have a research spike to investigate what our options are and what configuration bits we can manipulate.  For instance, can we use `launch.json` to enable/disable profilers (#264)? How about return results in a different format (#253, #294)? Can we set a specific connection to be active based an what the `launch.json` file says?

DOD:
  - The rest of the epic can be filled with existing issues that can live under this umbrella.

**Comment by Marwes** [comment]
> For instance, can we use launch.json to enable/disable profilers (https://github.com/influxdata/vsflux/issues/264)?

`launchRequest` seems to accept the configuration object defined in `launch.json` as is so we could add and define arbitrary options there to alter how the program is started (for profiling specifically we should be able to inject the profiling option into the script before starting it, see  #264 ). These options should also be defined  under `debugger.configurationAttributes` in `package.json` to show that we provide them (see https://github.com/microsoft/vscode-mock-debug ).

> How about return results in a different format (https://github.com/influxdata/vsflux/issues/253, https://github.com/influxdata/vsflux/issues/294)?

We already open the results in a webview so importing a graphing library to use for visualization ought to be simple enough #253 . Providing a button to copy CSV to clipboard ought to be simple enough with a bit of javascript as well.

> Can we set a specific connection to be active based an what the launch.json file says?

We currently select the "active" connection, but adding an optional parameter to the configuration object which names another connection should be easy enough.

**Comment by rockstar** [comment]
A summary of this research:

- When hitting F5, the registered debugger can use `launch.json` and other various techniques, e.g. commands, to get arguments and parameters for the debug environment.
- `launch.json`, in the root dir, is not really a viable solution for flux, for the following reasons:
  - Our execution environment could change regularly, from dev to stage to prod region.
  - The execution environment could change per directory of a project.
  - Our debugger should have several different parameters for enabling profilers, determining output (csv, graphs, tables, files). Mystery meat json is not a great user experience.
- Using commands to get arguments is pretty awkward, because you're still limited to the VSCode UI primitives. You could prompt and have users enter a string, or have a "quickpick", but there are UX concerns there. For instance, as the debugger becomes more complex, the user will be inundated with single parameters. Additionally, the quickpick dialog is not easily focusable, and doesn't have a great experience for selecting multiple things (like, say, various profilers).
- The debug interface for VSCode is very "local system" specific, and doesn't have a lot of configuration for the paradigm we have. As such, I propose the following:
  - On execution of a flux script, a new process is started which will present a custom UI with all the options made available. It requires a custom process because VSCode doesn't allow for custom dialogs.
  - This new process will communicate back to VSCode via IPC. An example of this interaction is the Color Picker extension. This IPC connection will then communicate the dynamic config of the debugger, rather than asking a user to write a `launch.json` file.

At this time, it's clear that working around VSCode issues makes this a pretty big lift. We have other things we'd like to focus on for the time being, so we'll come back to this work at a later time.

**Comment by Marwes** [comment]
Might it be worth it to just sand of the roughest edges here? Something like adding a default debugger config which can get auto completed when editing `launch.json` and preventing scripts from being closed when saving (as that happens when pressing F5).

That could be enough to make F5 at least work equivelent to the current right-click -> invoke script that we currently have.
