### ISSUE TITLE
Can't connect to Influx v1.X

### ISSUE THREAD

**Issue by theodiefenthal** [influxdata/vsflux#394]
I just installed the VS Code extension and successfully connected to InfluxDB cloud. 

Now, I wanted to add a second connection to an on premise Influx 1.8 database. According to the doc of Influx 1.8 that should be possible by switchting the influxdb type. https://docs.influxdata.com/influxdb/v1.8/tools/flux-vscode/ 

However, there is no such type switch in my vs code in the add connection dialog: 

![grafik](https://user-images.githubusercontent.com/4670569/162922032-0c00433b-2549-40b1-be23-9687691686e2.png)

If I try for the token something like `user:password` and as organziation my db name, clicking on the test or save button seems to have no effect at all. So I have no idea how to configure an Influx V1.X connection.

**Comment by rockstar** [comment]
InfluxDB v1.x support was removed.
