### ISSUE TITLE
Installing on CodeServer

### ISSUE THREAD

**Issue by lcardito** [influxdata/vsflux#396]
Hey team,

## TLD;DR
Is this extension supposed to work in a remote VS Code instance (code-server)?

## Details
I was curious to try out the vsflux extension, unfortunately tho at the moment I only have VS Code setup on a remote instance using [code server](https://github.com/coder/code-server) installed via the [linuxserver docker image](https://hub.docker.com/r/linuxserver/code-server).

### Environment
VSCode Server 

```
code-server: vUnknown
Code: 1.64.2
Commit: Unknown
Date: 2022-03-22T20:16:06.512Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36
```

Unfortunately when searching for the extension in the marketplace it doesn't even appear, I've tried to manually download the `vsix` file manually and the console spits up the following error:

```
[2022-04-13 13:09:36.746] [window] [error] Unable to install extension 'influxdata.flux' as it is not compatible with VS Code '1.64.2'.: Error: Unable to install extension 'influxdata.flux' as it is not compatible with VS Code '1.64.2'.
    at U.install (/app/code-server/lib/vscode/out/vs/server/node/server.main.js:146:90539)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Any suggestion? :)

Thanks!

**Comment by rockstar** [comment]
The current version of vsflux requires 1.65.0 or greater. Can you update your Code instance and try again?

**Comment by rockstar** [comment]
Thanks for your report! It piqued my interest enough to set up a remote Code server and try installing the plugin. `v1.0.4` installs great on the most recent Code server. We'll be more careful about revving the `engine` setting in `package.json` in the future.

As a result of this work, I've looked closer at #351. I'm currently blocked by an issue with the Eclipse Foundation account, but I'm hoping that we can resolve that relatively quickly. In the future, I'm hoping that we don't have to manually install `.vsix` files and we can just get it from the Open VSX marketplace.
