### ISSUE TITLE
Add the ability to browse measurements

### ISSUE THREAD

**Issue by russorat** [influxdata/vsflux#69]
trying to open a bucket results in 
`Getting tag keys for bucket: telegraf Err: StatusCodeError: 404 - “{\“code\“:\“not found\“,\“message\“:\“failed to initialize execute state: could not find bucket \\\“buck1\\\“\”}“`

**Comment by russorat** [comment]
i think this might be fixed with https://github.com/influxdata/vsflux/pull/71

**Comment by kelwang** [comment]
yes. sorry about that
