### ISSUE TITLE
Display script syntax errors inline with the code

### ISSUE THREAD

**Issue by russorat** [influxdata/vsflux#70]
A user should be able to verify the syntax of their script is right before running it.

**Comment by kelwang** [comment]
Hi @russorat, could paste some examples for this one. 

We should be able to display errors. But certain errors might not be displayed, so need more details to investigate.

**Comment by russorat** [comment]
oops, i guess you do already. Is there any way to do it without sending it to a configured influxdb?

![image](https://user-images.githubusercontent.com/4805997/72641429-0c383100-391f-11ea-988d-8429ccd0c47c.png)

**Comment by jademcgough** [comment]
> Is there any way to do it without sending it to a configured influxdb?

It doesn't require a configured influxdb; when the document saves we check script validity through the language server.

I think there are still some cases where invalid scripts aren't being caught by the LS, so if you find any instances of that, feel free to file issues.

**Comment by kelwang** [comment]
Okay, so blocking running the query if flux parsing failed

**Comment by bthesorceror** [comment]
I think the ask from @russorat is solved now (no request is made to influxdb the LSP handles this), can we close this ticket?
