### ISSUE TITLE
1.x influxdb integration support

### ISSUE THREAD

**Issue by jademcgough** [influxdata/vsflux#74]
The influxdb integration is only designed to support 2.0 currently, but flux queries can be sent over the 1.x influxdb API: https://docs.influxdata.com/flux/v0.50/guides/executing-queries/#influxdb-api

As a user, I should be able to choose what version of influxdb to connect to (2.0 or 1.7+).

If I choose 1.7+, the API token field should be hidden from settings, and I should see fields to enter my username and password.

**Comment by lephisto** [comment]
yeah, i need this. is there a way to trick the vscode extension to work with 1.7?

**Comment by jademcgough** [comment]
@lephisto There's not really a workaround that I'm aware of. We'll be prioritizing this soon.

**Comment by lephisto** [comment]
@jademcgough I tried to find those settings, but i guess it's somewhere hidden in vscodes central config database, which is not a plaintext thing.

**Comment by jademcgough** [comment]
@lephisto there are no settings for this yet, the work has not been done.

**Comment by lephisto** [comment]
Allright, looking forward to that. It's a real pain to develop moderate complex flux queries w/ Chronograf.. And for my production purposes I cannot do Influx2 yet..
