### ISSUE TITLE
Show configuration errors above input fields

### ISSUE THREAD

**Issue by jademcgough** [influxdata/vsflux#80]
When forms inputs are invalid, we show that information at the bottom of the configuration view:

<img width="323" alt="Screen Shot 2020-02-05 at 3 35 53 AM" src="https://user-images.githubusercontent.com/1147449/73838492-a5dd5a80-47c8-11ea-893b-aa12d9a1b6d8.png">

Instead of writing our own custom validation javascript, we should instead use [html5 form validation](https://pageclip.co/blog/2018-02-20-you-should-use-html5-form-validation.html) to do validation for us, which will show configuration errors with their relevant input fields.

**Comment by kelwang** [comment]
have experienced some trouble to show up html validation error message in vscode, not sure if that related to some security flags been experienced before. But the general customized javascript should work as expected.
