### ISSUE TITLE
change connection commands

### ISSUE THREAD

**Issue by jademcgough** [influxdata/vsflux#83]
We currently display these three commands when right clicking on a connection:
<img width="264" alt="Screen Shot 2020-02-05 at 9 16 22 AM" src="https://user-images.githubusercontent.com/1147449/73865591-5b73d200-47f8-11ea-8f33-be8c63876a6a.png">

1. When a user chooses "delete connection", they should have to confirm this in a modal before the connection is deleted.
1. Remove the "Run Query" command.
1. Add a "Connect" command, which will make that the active connection. If possible we could hide this for the currently active connection.
1. The command order should be:
    Connect
    Edit Configuration
    Delete

**Comment by kelwang** [comment]
i will hold on the request 3.  Because, left click will already do the switch.

**Comment by jademcgough** [comment]
@kelwang I was worried it wouldn't be obvious how to make a connection active, but the UX is really clear, so I'm fine with skipping 3
